---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Зарегистрированный пользователь должен иметь возможность авторизоваться
  - Пользователь должен иметь возможность выбора языка программирования
  - Пользователь должен иметь возможность выбра языка интерфейса
  - В игре должны участвовоать два игрока, один из которых может быть ботом
  - Пользователь должен иметь возможность выбора соперника - бота, произвольного игрока, выбранного игрока
  - Пользователь находится в режиме ожидания второго игрока до тех пор, пока второй игрок или бот не подключится к игре
  - Каждый игрок должен видеть задание и время игры
  - Каждый игрок должен видеть код своего соперника в режиме он-лайн.
  - Каждый игрок должен иметь возможность для неограниченного количества проверок своего решения
  - Когда один из игроков находит верное решение, обоим игрокам должно высвечиваться модальное окно с сообщением о победителе игры.
  - Победитель-игрок должен иметь возможность выйти из игры. 
  - Игрок-победитель не может больше проверять свой код, но код должен быть доступен ему для просмотра.
  - Проигравший должен иметь возможность выйти или доиграть до конца.
  - Когда оба игрока вышли, игра считается полностью законченной и должна удалятся из памяти.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - на сайте должна быть указана информация о разработчике сайта
  
